#@TYPE: Machine
#@NAME: phyverso-evcs-am62xx-1-k3r5
#@DESCRIPTION: PHYTEC phyVERSO-EVSE AM62x, 2 GB RAM, HS-FS (R5F)
#@ARTICLENUMBERS: PV-04925-100.A0, KSP-0728-FF.A1, PCM-071-KSM02.A0 (5432DE11I)

require conf/machine/include/phyam62xx-k3r5.inc

MACHINEOVERRIDES =. "k3r5-am62xx:phyverso-evcs:"

SPL_BINARY = "tiboot3-am62x-hs-fs-phycore-som.bin"

UBOOT_MACHINE = ""
# Last config in the list is default
UBOOT_CONFIG = "ethboot sd"
UBOOT_CONFIG[sd] = "phycore_am62x_r5_defconfig,sdcard"
UBOOT_CONFIG[ethboot] = "phycore_am62x_r5_ethboot_defconfig"
