######################################################################
# Compiler / Cross-Compiler Declarations:                            #
######################################################################
include ../../../CompilerDeclaration

all:

	$(MAKE) -C "osal" all
	$(MAKE) -C "comm_mgr" all
	$(MAKE) -C "mem_pool" all


clean:

	$(MAKE) -C "osal" clean
	$(MAKE) -C "comm_mgr" clean
	$(MAKE) -C "mem_pool" clean

