######################################################################
# Compiler / Cross-Compiler Declarations:                            #
######################################################################
include ../../CompilerDeclaration

all:

	$(MAKE) -C "FFT" all


clean:

	$(MAKE) -C "FFT" clean