all:
	$(MAKE) -C management_tool all
	$(MAKE) -C host_loading_service all
	$(MAKE) -C ind_listener_app all

clean:
	$(MAKE) -C host_loading_service clean
	$(MAKE) -C management_tool clean
	$(MAKE) -C ind_listener_app clean
